name: build
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'firmware/**'
      - 'scripts/**'
      - 'README.md'
      - '.gitignore'
permissions: write-all      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Compile
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp8266:esp8266:nodemcuv2
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
        required-libraries: ArduinoJson,Adafruit NeoPixel,Adafruit NeoMatrix,DS3231,WiFiManager,Adafruit GFX Library
    - name: Read VERSION file
      id: getversion
      if: github.ref == 'refs/heads/main'
      run: echo "::set-output name=version::$(cat VERSION)"
    - name: Update version
      if: github.ref == 'refs/heads/main'
      run: echo "`jq '.version=${{ steps.getversion.outputs.version }}' firmware/version.json`" > firmware.version.json
    - name: Commit new firmware version
      if: github.ref == 'refs/heads/main'
      run: |
        mv $HOME/wordclock/build/esp8266.esp8266.nodemcuv2/wordclock.ino.bin firmware/
        git config --global user.name 'laurensV'
        git config --global user.email 'laurensv@users.noreply.github.com'
        git add firmware
        git commit -m "Add new firmware"
        git push
        
